using Raylib_cs;
using Prowl.Wicked.Core;
using Prowl.Wicked.Network;
using Prowl.Wicked.Transport.Telepathy;
using ShooterGame;
using System.Numerics;

// Game settings
const int ScreenWidth = 800;
const int ScreenHeight = 600;
const int DefaultPort = 7777;

// Game state
GameState gameState = GameState.Menu;
string inputText = "";
bool isTypingIp = false;
string statusMessage = "";

// Initialize Raylib
Raylib.InitWindow(ScreenWidth, ScreenHeight, "Prowl.Wicked Shooter - Press H to Host, J to Join");
Raylib.SetTargetFPS(60);

// Initialize networking
var transport = new TelepathyTransport();
NetworkManager.Initialize(transport);

// RPC handlers are automatically generated by the IL weaver
// No manual registration needed when using [Command] and [ClientRpc] attributes

// Subscribe to network events
NetworkManager.OnNetworkStarted += mode =>
{
    statusMessage = $"Started as {mode}";
    gameState = GameState.Playing;

    if (NetworkManager.IsServer)
    {
        // Spawn the local player for host
        SpawnLocalPlayer();
    }
};

NetworkManager.OnNetworkStopped += () =>
{
    statusMessage = "Disconnected";
    gameState = GameState.Menu;
};

NetworkServer.OnClientConnected += conn =>
{
    Console.WriteLine($"Client {conn.ConnectionId} connected");
    // Create entity, add behaviour, THEN spawn (like Unity prefabs)
    var player = NetworkManager.CreateDeferred();
    player.AddBehaviour<PlayerBehaviour>();
    NetworkManager.FinalizeSpawn(player, conn, isLocalPlayer: true);
};

NetworkClient.OnConnected += () =>
{
    statusMessage = "Connected to server!";
};

// Main game loop
while (!Raylib.WindowShouldClose())
{
    float deltaTime = Raylib.GetFrameTime();

    // Update
    switch (gameState)
    {
        case GameState.Menu:
            UpdateMenu();
            break;
        case GameState.Playing:
            UpdateGame(deltaTime);
            break;
    }

    // Draw
    Raylib.BeginDrawing();
    Raylib.ClearBackground(Color.DarkGray);

    switch (gameState)
    {
        case GameState.Menu:
            DrawMenu();
            break;
        case GameState.Playing:
            DrawGame();
            break;
    }

    // Always show status
    if (!string.IsNullOrEmpty(statusMessage))
    {
        Raylib.DrawText(statusMessage, 10, ScreenHeight - 25, 16, Color.Yellow);
    }

    Raylib.EndDrawing();
}

// Cleanup
NetworkManager.Shutdown();
Raylib.CloseWindow();

// ============ Menu Functions ============

void UpdateMenu()
{
    // Handle keyboard input for IP address
    if (isTypingIp)
    {
        int key = Raylib.GetCharPressed();
        while (key > 0)
        {
            if (key >= 32 && key <= 126 && inputText.Length < 20)
            {
                inputText += (char)key;
            }
            key = Raylib.GetCharPressed();
        }

        if (Raylib.IsKeyPressed(KeyboardKey.Backspace) && inputText.Length > 0)
        {
            inputText = inputText[..^1];
        }

        if (Raylib.IsKeyPressed(KeyboardKey.Enter))
        {
            string ip = string.IsNullOrEmpty(inputText) ? "localhost" : inputText;
            statusMessage = $"Connecting to {ip}...";
            NetworkManager.StartClient(ip, DefaultPort);
            isTypingIp = false;
        }

        if (Raylib.IsKeyPressed(KeyboardKey.Escape))
        {
            isTypingIp = false;
            inputText = "";
        }
    }
    else
    {
        if (Raylib.IsKeyPressed(KeyboardKey.H))
        {
            statusMessage = "Starting host...";
            NetworkManager.StartHost(DefaultPort);
        }

        if (Raylib.IsKeyPressed(KeyboardKey.J))
        {
            isTypingIp = true;
            inputText = "";
            statusMessage = "Enter server IP (or press Enter for localhost):";
        }
    }
}

void DrawMenu()
{
    // Title
    Raylib.DrawText("PROWL.WICKED SHOOTER", ScreenWidth / 2 - 180, 100, 30, Color.White);
    Raylib.DrawText("A Networked Multiplayer Demo", ScreenWidth / 2 - 140, 140, 16, Color.LightGray);

    // Instructions
    int y = 250;
    Raylib.DrawText("Controls:", ScreenWidth / 2 - 60, y, 20, Color.Yellow);
    y += 35;

    if (isTypingIp)
    {
        Raylib.DrawText("Enter IP Address:", ScreenWidth / 2 - 80, y, 18, Color.White);
        y += 30;

        // Draw input box
        Raylib.DrawRectangle(ScreenWidth / 2 - 100, y, 200, 30, Color.DarkBlue);
        Raylib.DrawRectangleLines(ScreenWidth / 2 - 100, y, 200, 30, Color.White);
        Raylib.DrawText(inputText + "_", ScreenWidth / 2 - 90, y + 7, 16, Color.White);
        y += 50;

        Raylib.DrawText("Press ENTER to connect, ESC to cancel", ScreenWidth / 2 - 150, y, 14, Color.Gray);
    }
    else
    {
        Raylib.DrawText("[H] Host a Game", ScreenWidth / 2 - 70, y, 18, Color.Green);
        y += 30;
        Raylib.DrawText("[J] Join a Game", ScreenWidth / 2 - 70, y, 18, Color.SkyBlue);
        y += 50;

        Raylib.DrawText("In-Game Controls:", ScreenWidth / 2 - 80, y, 18, Color.Yellow);
        y += 25;
        Raylib.DrawText("WASD / Arrows - Move", ScreenWidth / 2 - 90, y, 16, Color.LightGray);
        y += 22;
        Raylib.DrawText("Left Click - Shoot", ScreenWidth / 2 - 90, y, 16, Color.LightGray);
        y += 22;
        Raylib.DrawText("V - Spawn Vehicle", ScreenWidth / 2 - 90, y, 16, Color.LightGray);
        y += 22;
        Raylib.DrawText("F - Enter/Exit Vehicle", ScreenWidth / 2 - 90, y, 16, Color.LightGray);
        y += 22;
        Raylib.DrawText("ESC - Disconnect", ScreenWidth / 2 - 90, y, 16, Color.LightGray);
    }
}

// ============ Game Functions ============

void UpdateGame(float deltaTime)
{
    // Disconnect on ESC
    if (Raylib.IsKeyPressed(KeyboardKey.Escape))
    {
        NetworkManager.Stop();
        return;
    }

    // Tick the game loop
    GameLoop.Tick(deltaTime);
}

void DrawGame()
{
    // Draw all entities
    if (World.Active == null) return;

    // Build set of players who are in vehicles (don't draw them separately)
    HashSet<uint> playersInVehicles = new();
    foreach (var entity in World.Active.Entities.Values)
    {
        var vehicle = entity.GetBehaviour<VehicleBehaviour>();
        if (vehicle != null && vehicle.HasDriver)
        {
            playersInVehicles.Add(vehicle.DriverNetId);
        }
    }

    // Draw vehicles first
    foreach (var entity in World.Active.Entities.Values)
    {
        var vehicle = entity.GetBehaviour<VehicleBehaviour>();
        if (vehicle != null)
        {
            DrawVehicle(vehicle);
            continue;
        }
    }

    // Draw players (skip those in vehicles)
    foreach (var entity in World.Active.Entities.Values)
    {
        var player = entity.GetBehaviour<PlayerBehaviour>();
        if (player != null)
        {
            // Skip drawing player if they're in a vehicle
            if (playersInVehicles.Contains(entity.NetId))
                continue;

            DrawPlayer(player);
            continue;
        }

        var bullet = entity.GetBehaviour<BulletBehaviour>();
        if (bullet != null)
        {
            DrawBullet(bullet);
        }
    }

    // Draw UI
    DrawGameUI();
}

void DrawPlayer(PlayerBehaviour player)
{
    // Convert synced color to Raylib Color
    uint c = player.PlayerColor;
    Color color = new Color(
        (byte)((c >> 16) & 0xFF),
        (byte)((c >> 8) & 0xFF),
        (byte)(c & 0xFF),
        (byte)255
    );

    // Draw player circle
    float radius = 15f;
    Raylib.DrawCircle((int)player.DisplayX, (int)player.DisplayY, radius, color);

    // Draw outline for local player
    if (player.IsLocalPlayer)
    {
        Raylib.DrawCircleLines((int)player.DisplayX, (int)player.DisplayY, radius + 3, Color.White);
    }

    // Draw health bar
    float healthBarWidth = 30f;
    float healthBarHeight = 4f;
    float healthPercent = player.Health / PlayerBehaviour.MaxHealth;
    float barX = player.DisplayX - healthBarWidth / 2;
    float barY = player.DisplayY - radius - 10;

    Raylib.DrawRectangle((int)barX, (int)barY, (int)healthBarWidth, (int)healthBarHeight, Color.DarkGray);
    Raylib.DrawRectangle((int)barX, (int)barY, (int)(healthBarWidth * healthPercent), (int)healthBarHeight,
        healthPercent > 0.5f ? Color.Green : healthPercent > 0.25f ? Color.Yellow : Color.Red);

    // Draw player name/ID
    string label = player.IsLocalPlayer ? "YOU" : $"P{player.NetId}";
    int textWidth = Raylib.MeasureText(label, 12);
    Raylib.DrawText(label, (int)(player.DisplayX - textWidth / 2), (int)(player.DisplayY + radius + 5), 12, Color.White);
}

void DrawBullet(BulletBehaviour bullet)
{
    uint c = bullet.BulletColor;
    Color color = new Color(
        (byte)((c >> 16) & 0xFF),
        (byte)((c >> 8) & 0xFF),
        (byte)(c & 0xFF),
        (byte)255
    );

    Raylib.DrawCircle((int)bullet.X, (int)bullet.Y, BulletBehaviour.Radius, color);
}

void DrawVehicle(VehicleBehaviour vehicle)
{
    uint c = vehicle.VehicleColor;
    Color color = new Color(
        (byte)((c >> 16) & 0xFF),
        (byte)((c >> 8) & 0xFF),
        (byte)(c & 0xFF),
        (byte)255
    );

    float x = vehicle.DisplayX;
    float y = vehicle.DisplayY;
    float w = VehicleBehaviour.Width;
    float h = VehicleBehaviour.Height;

    // Draw vehicle body (rectangle)
    Raylib.DrawRectangle((int)(x - w / 2), (int)(y - h / 2), (int)w, (int)h, color);

    // Draw cabin/roof (smaller rectangle on top)
    Color roofColor = new Color(
        (byte)Math.Min(255, ((c >> 16) & 0xFF) + 30),
        (byte)Math.Min(255, ((c >> 8) & 0xFF) + 30),
        (byte)Math.Min(255, (c & 0xFF) + 30),
        (byte)255
    );
    Raylib.DrawRectangle((int)(x - w / 4), (int)(y - h / 3), (int)(w / 2), (int)(h / 1.5f), roofColor);

    // Draw wheels (4 small dark rectangles at corners)
    Color wheelColor = Color.DarkGray;
    int wheelW = 10;
    int wheelH = 6;
    // Front left
    Raylib.DrawRectangle((int)(x - w / 2 - 2), (int)(y - h / 2 + 2), wheelW, wheelH, wheelColor);
    // Front right
    Raylib.DrawRectangle((int)(x + w / 2 - wheelW + 2), (int)(y - h / 2 + 2), wheelW, wheelH, wheelColor);
    // Back left
    Raylib.DrawRectangle((int)(x - w / 2 - 2), (int)(y + h / 2 - wheelH - 2), wheelW, wheelH, wheelColor);
    // Back right
    Raylib.DrawRectangle((int)(x + w / 2 - wheelW + 2), (int)(y + h / 2 - wheelH - 2), wheelW, wheelH, wheelColor);

    // If owned by local player, draw outline
    if (vehicle.IsOwned)
    {
        Raylib.DrawRectangleLines((int)(x - w / 2 - 2), (int)(y - h / 2 - 2), (int)(w + 4), (int)(h + 4), Color.White);
    }

    // Draw driver indicator if someone is driving
    if (vehicle.HasDriver)
    {
        // Find the driver's color
        var driverEntity = World.Active?.FindEntity(vehicle.DriverNetId);
        var driverBehaviour = driverEntity?.GetBehaviour<PlayerBehaviour>();
        if (driverBehaviour != null)
        {
            uint dc = driverBehaviour.PlayerColor;
            Color driverColor = new Color(
                (byte)((dc >> 16) & 0xFF),
                (byte)((dc >> 8) & 0xFF),
                (byte)(dc & 0xFF),
                (byte)255
            );
            // Small circle showing who's driving
            Raylib.DrawCircle((int)(x), (int)(y), 8, driverColor);
        }
    }

    // Draw health bar above vehicle
    float healthBarWidth = w;
    float healthBarHeight = 5f;
    float healthPercent = vehicle.Health / VehicleBehaviour.MaxHealth;
    float barX = x - healthBarWidth / 2;
    float barY = y - h / 2 - 12;

    Raylib.DrawRectangle((int)barX, (int)barY, (int)healthBarWidth, (int)healthBarHeight, Color.DarkGray);
    Raylib.DrawRectangle((int)barX, (int)barY, (int)(healthBarWidth * healthPercent), (int)healthBarHeight,
        healthPercent > 0.5f ? Color.Green : healthPercent > 0.25f ? Color.Yellow : Color.Red);

    // Draw label
    string label = vehicle.HasDriver ? $"V{vehicle.NetId} (P{vehicle.DriverNetId})" : $"V{vehicle.NetId}";
    int textWidth = Raylib.MeasureText(label, 12);
    Raylib.DrawText(label, (int)(x - textWidth / 2), (int)(y + h / 2 + 8), 12, Color.White);
}

void DrawGameUI()
{
    // Connection info
    string modeText = NetworkManager.IsHost ? "HOST" : NetworkManager.IsServer ? "SERVER" : "CLIENT";
    Raylib.DrawText(modeText, 10, 10, 20, Color.White);

    // Player count
    int playerCount = 0;
    int vehicleCount = 0;
    if (World.Active != null)
    {
        foreach (var e in World.Active.Entities.Values)
        {
            if (e.GetBehaviour<PlayerBehaviour>() != null)
                playerCount++;
            if (e.GetBehaviour<VehicleBehaviour>() != null)
                vehicleCount++;
        }
    }
    Raylib.DrawText($"Players: {playerCount}", 10, 35, 16, Color.LightGray);
    Raylib.DrawText($"Vehicles: {vehicleCount}", 10, 55, 16, Color.LightGray);

    // Local player health and status
    if (World.Active != null)
    {
        foreach (var e in World.Active.Entities.Values)
        {
            var player = e.GetBehaviour<PlayerBehaviour>();
            if (player != null && player.IsLocalPlayer)
            {
                Raylib.DrawText($"Health: {(int)player.Health}", 10, 75, 16, Color.Green);

                // Check if in a vehicle
                bool inVehicle = false;
                foreach (var ve in World.Active.Entities.Values)
                {
                    var vehicle = ve.GetBehaviour<VehicleBehaviour>();
                    if (vehicle != null && vehicle.DriverNetId == player.NetId)
                    {
                        inVehicle = true;
                        Raylib.DrawText($"Driving Vehicle {ve.NetId}", 10, 95, 16, Color.SkyBlue);
                        break;
                    }
                }
                if (!inVehicle)
                {
                    Raylib.DrawText("V - Spawn Vehicle", 10, 95, 14, Color.Gray);
                    Raylib.DrawText("F - Enter nearby vehicle", 10, 112, 14, Color.Gray);
                }
                else
                {
                    Raylib.DrawText("F - Exit Vehicle", 10, 112, 14, Color.Gray);
                }
                break;
            }
        }
    }

    // Instructions
    Raylib.DrawText("ESC to disconnect", ScreenWidth - 150, 10, 14, Color.Gray);
}

void SpawnLocalPlayer()
{
    if (!NetworkManager.IsServer) return;

    // Create entity, add behaviour, THEN spawn (like Unity prefabs)
    var player = NetworkManager.CreateDeferred();
    player.AddBehaviour<PlayerBehaviour>();
    NetworkManager.FinalizeSpawn(player, NetworkServer.LocalConnection, isLocalPlayer: true);
}

// Enum must be declared after top-level statements
enum GameState { Menu, Playing }
