<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <IsPackable>false</IsPackable>
        <RootNamespace>Prowl.Graphite.Debugger.Tests</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\Graphite\Prowl.Graphite.csproj" />
        <ProjectReference Include="..\..\Debugger\Core\Prowl.Graphite.Debugger.csproj" />
        <ProjectReference Include="..\..\ShaderDef\Core\Prowl.Graphite.ShaderDef.csproj" />
        <ProjectReference Include="..\..\ShaderDef\Compiler\Prowl.Graphite.ShaderDef.Compiler.csproj" />
    </ItemGroup>

    <ItemGroup>
        <Content Include="..\Graphite\Shaders\FullScreenTriSampleTexture2D.slang" Link="Shaders\FullScreenTriSampleTexture2D.slang" CopyToOutputDirectory="PreserveNewest" />
        <Content Include="..\Graphite\Shaders\ComputeTextureGenerator.slang" Link="Shaders\ComputeTextureGenerator.slang" CopyToOutputDirectory="PreserveNewest" />
    </ItemGroup>

</Project>
